//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorsSchedule
    {
        public int ID_записи { get; set; }
        public Nullable<int> ID_врача { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<System.TimeSpan> Время_начала { get; set; }
        public Nullable<System.TimeSpan> Время_окончания { get; set; }
        public string Доступность { get; set; }
    
        public virtual Doctors Doctors { get; set; }
    }
}
