//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patients()
        {
            this.Appointments = new HashSet<Appointments>();
        }
    
        public int ID_пациента { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public string Адрес { get; set; }
        public string Номер_телефона { get; set; }
        public string Паспортные_данные { get; set; }
        public string Пол { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public Nullable<int> ID_участка { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointments> Appointments { get; set; }
        public virtual ClinicDepartments ClinicDepartments { get; set; }
    }
}
